// @routes-hash 95aef9485eaa612801edbae68e822cca
import { Express } from "express";

import route1 from "./routes/agent/run/detail";
import route2 from "./routes/agent/run/status";
import route3 from "./routes/agents/clearMemory";
import route4 from "./routes/agents/getMemory";
import route5 from "./routes/artStyle/addArtStyle";
import route6 from "./routes/artStyle/editArtStyle";
import route7 from "./routes/artStyle/extractStylePrompt";
import route8 from "./routes/artStyle/getArtStyle";
import route9 from "./routes/assets/addAssets";
import route10 from "./routes/assets/addAudioAssets";
import route11 from "./routes/assets/batchDelete";
import route12 from "./routes/assets/batchGenerationData";
import route13 from "./routes/assets/delAssets";
import route14 from "./routes/assets/delImage";
import route15 from "./routes/assets/foundation/generate";
import route16 from "./routes/assets/generateAssets";
import route17 from "./routes/assets/getAssetsApi";
import route18 from "./routes/assets/getImage";
import route19 from "./routes/assets/getMaterialData";
import route20 from "./routes/assets/polishAssetsPrompt";
import route21 from "./routes/assets/pollingImageAssets";
import route22 from "./routes/assets/pollingPromptAssets";
import route23 from "./routes/assets/saveAssets";
import route24 from "./routes/assets/updateAssets";
import route25 from "./routes/assets/updateAudioAssets";
import route26 from "./routes/assets/uploadClip";
import route27 from "./routes/assetsGenerate/batchGenerateImageAssets";
import route28 from "./routes/assetsGenerate/batchPolishAssetsPrompt";
import route29 from "./routes/assetsGenerate/cancelGenerate";
import route30 from "./routes/assetsGenerate/generateAssets";
import route31 from "./routes/assetsGenerate/polishAssetsPrompt";
import route32 from "./routes/common/getBigImage";
import route33 from "./routes/cornerScape/batchBindAudio";
import route34 from "./routes/cornerScape/getAllAssets";
import route35 from "./routes/cornerScape/pollingAudio";
import route36 from "./routes/cornerScape/updateAssetsAudio";
import route37 from "./routes/diagnostics/logs/cleanup";
import route38 from "./routes/diagnostics/logs/export";
import route39 from "./routes/diagnostics/logs/status";
import route40 from "./routes/diagnostics/runtime/status";
import route41 from "./routes/general/generalStatistics";
import route42 from "./routes/general/getSingleProject";
import route43 from "./routes/general/updateProject";
import route44 from "./routes/login/login";
import route45 from "./routes/modelSelect/getModelDetail";
import route46 from "./routes/modelSelect/getModelList";
import route47 from "./routes/novel/addNovel";
import route48 from "./routes/novel/batchDeleteNovel";
import route49 from "./routes/novel/delNovel";
import route50 from "./routes/novel/event/batchDeleteEvent";
import route51 from "./routes/novel/event/deletEvent";
import route52 from "./routes/novel/event/generateEvents";
import route53 from "./routes/novel/event/getEvent";
import route54 from "./routes/novel/getNovel";
import route55 from "./routes/novel/getNovelData";
import route56 from "./routes/novel/getNovelEventState";
import route57 from "./routes/novel/getNovelIndex";
import route58 from "./routes/novel/updateNovel";
import route59 from "./routes/other/deleteAllData";
import route60 from "./routes/other/getVersion";
import route61 from "./routes/production/assets/addDeriveAsset";
import route62 from "./routes/production/assets/batchGenerateAssetsImage";
import route63 from "./routes/production/assets/deleteAssetsDireve";
import route64 from "./routes/production/assets/pollingImage";
import route65 from "./routes/production/assets/updateAssetsUrl";
import route66 from "./routes/production/editImage/createDirectorAsset";
import route67 from "./routes/production/editImage/generateFlowImage";
import route68 from "./routes/production/editImage/generateFlowImageTask";
import route69 from "./routes/production/editImage/getAssetImageHistory";
import route70 from "./routes/production/editImage/getImageDefaultModle";
import route71 from "./routes/production/editImage/getImageFlow";
import route72 from "./routes/production/editImage/getImageHistory";
import route73 from "./routes/production/editImage/pollImageTask";
import route74 from "./routes/production/editImage/saveImageFlow";
import route75 from "./routes/production/editImage/updateImageFlow";
import route76 from "./routes/production/editImage/uploadImage";
import route77 from "./routes/production/editImage/uploadMedia";
import route78 from "./routes/production/getFlowData";
import route79 from "./routes/production/getStoryboardData";
import route80 from "./routes/production/music/bible/detail";
import route81 from "./routes/production/music/bible/generate";
import route82 from "./routes/production/music/bible/list";
import route83 from "./routes/production/music/bible/review";
import route84 from "./routes/production/music/cue/bind";
import route85 from "./routes/production/music/cue/compilePrompt";
import route86 from "./routes/production/music/cue/generate";
import route87 from "./routes/production/music/cue/list";
import route88 from "./routes/production/music/cue/prompt/list";
import route89 from "./routes/production/music/cue/prompt/save";
import route90 from "./routes/production/music/cue/reviewPrompt";
import route91 from "./routes/production/music/cue/selectAsset";
import route92 from "./routes/production/music/library/compilePrompt";
import route93 from "./routes/production/music/library/create";
import route94 from "./routes/production/music/library/detail";
import route95 from "./routes/production/music/library/edition/save";
import route96 from "./routes/production/music/library/generate";
import route97 from "./routes/production/music/library/list";
import route98 from "./routes/production/music/library/lyrics/confirm";
import route99 from "./routes/production/music/library/lyrics/generate";
import route100 from "./routes/production/music/library/lyrics/list";
import route101 from "./routes/production/music/library/lyrics/review";
import route102 from "./routes/production/music/library/lyrics/save";
import route103 from "./routes/production/music/library/prompt/list";
import route104 from "./routes/production/music/library/prompt/save";
import route105 from "./routes/production/music/library/reviewPrompt";
import route106 from "./routes/production/music/library/selectVersion";
import route107 from "./routes/production/music/library/trim";
import route108 from "./routes/production/music/plan/detail";
import route109 from "./routes/production/music/plan/generate";
import route110 from "./routes/production/music/plan/list";
import route111 from "./routes/production/music/plan/review";
import route112 from "./routes/production/review/accept";
import route113 from "./routes/production/review/createFeedback";
import route114 from "./routes/production/review/detail";
import route115 from "./routes/production/review/ignore";
import route116 from "./routes/production/review/list";
import route117 from "./routes/production/review/recalculate";
import route118 from "./routes/production/review/resolveBatch";
import route119 from "./routes/production/review/rollback";
import route120 from "./routes/production/saveFlowData";
import route121 from "./routes/production/storyboard/addStoryboard";
import route122 from "./routes/production/storyboard/applyStoryboardTableReview";
import route123 from "./routes/production/storyboard/batchAddStoryboardInfo";
import route124 from "./routes/production/storyboard/batchDelete";
import route125 from "./routes/production/storyboard/batchGenerateImage";
import route126 from "./routes/production/storyboard/downPreviewImage";
import route127 from "./routes/production/storyboard/editStoryboardInfo";
import route128 from "./routes/production/storyboard/getStoryboardData";
import route129 from "./routes/production/storyboard/pollingImage";
import route130 from "./routes/production/storyboard/previewImage";
import route131 from "./routes/production/storyboard/removeFrame";
import route132 from "./routes/production/storyboard/restructureStoryboardTable";
import route133 from "./routes/production/storyboard/reviewStoryboardTable";
import route134 from "./routes/production/storyboard/updateStoryboardUrl";
import route135 from "./routes/production/workbench/addTrack";
import route136 from "./routes/production/workbench/applyVideoTrackReview";
import route137 from "./routes/production/workbench/batchGeneratePrompt";
import route138 from "./routes/production/workbench/batchGenerateVideo";
import route139 from "./routes/production/workbench/cancelVideoGenerationTask";
import route140 from "./routes/production/workbench/checkVideoPrompt";
import route141 from "./routes/production/workbench/checkVideoStateList";
import route142 from "./routes/production/workbench/createMergedReference";
import route143 from "./routes/production/workbench/deleteTrack";
import route144 from "./routes/production/workbench/delVideo";
import route145 from "./routes/production/workbench/generateVideo";
import route146 from "./routes/production/workbench/generateVideoPrompt";
import route147 from "./routes/production/workbench/getAudioBindAssetsList";
import route148 from "./routes/production/workbench/getFileUrl";
import route149 from "./routes/production/workbench/getGenerateData";
import route150 from "./routes/production/workbench/getVideoList";
import route151 from "./routes/production/workbench/reviewVideoTracks";
import route152 from "./routes/production/workbench/selectVideo";
import route153 from "./routes/production/workbench/updateVideoDuration";
import route154 from "./routes/production/workbench/updateVideoPrompt";
import route155 from "./routes/project/addDirectorManual";
import route156 from "./routes/project/addProject";
import route157 from "./routes/project/addVisualManual";
import route158 from "./routes/project/contextPack/generate";
import route159 from "./routes/project/contextPack/get";
import route160 from "./routes/project/deleteDirectorManual";
import route161 from "./routes/project/deleteVisualManual";
import route162 from "./routes/project/delProject";
import route163 from "./routes/project/editDirectorlManual";
import route164 from "./routes/project/editProject";
import route165 from "./routes/project/editVisualManual";
import route166 from "./routes/project/getModelDetails";
import route167 from "./routes/project/getProject";
import route168 from "./routes/project/getVisualManual";
import route169 from "./routes/project/importPortableProject";
import route170 from "./routes/project/material/delete";
import route171 from "./routes/project/material/list";
import route172 from "./routes/project/material/read";
import route173 from "./routes/project/material/upload";
import route174 from "./routes/project/preparePortableCopy";
import route175 from "./routes/project/queryDirectorManual";
import route176 from "./routes/project/visualManual";
import route177 from "./routes/script/addScript";
import route178 from "./routes/script/batchAddScript";
import route179 from "./routes/script/delScript";
import route180 from "./routes/script/exportScript";
import route181 from "./routes/script/extractAssets";
import route182 from "./routes/script/getAiRegex";
import route183 from "./routes/script/getScrptApi";
import route184 from "./routes/script/pollScriptAssets";
import route185 from "./routes/script/updateScript";
import route186 from "./routes/scriptAgent/deleteScript";
import route187 from "./routes/scriptAgent/saveWorkspaceStage";
import route188 from "./routes/scriptAgent/upsertScript";
import route189 from "./routes/scriptAgent/workspaceDetail";
import route190 from "./routes/setting/about/checkUpdate";
import route191 from "./routes/setting/about/downloadApp";
import route192 from "./routes/setting/agentDeploy/agentSetKey";
import route193 from "./routes/setting/agentDeploy/deployAgentModel";
import route194 from "./routes/setting/agentDeploy/getAgentDeploy";
import route195 from "./routes/setting/agentDeploy/getAgentUseMode";
import route196 from "./routes/setting/agentDeploy/updateUseMode";
import route197 from "./routes/setting/dbConfig/clearData";
import route198 from "./routes/setting/dbConfig/clearTable";
import route199 from "./routes/setting/dbConfig/dbInfo";
import route200 from "./routes/setting/dbConfig/exportData";
import route201 from "./routes/setting/dbConfig/importData";
import route202 from "./routes/setting/dev/getSwitchAiDevTool";
import route203 from "./routes/setting/dev/updateSwitchAiDevTool";
import route204 from "./routes/setting/dreamina/install";
import route205 from "./routes/setting/dreamina/listTask";
import route206 from "./routes/setting/dreamina/login";
import route207 from "./routes/setting/dreamina/logout";
import route208 from "./routes/setting/dreamina/queryResult";
import route209 from "./routes/setting/dreamina/queueStatus";
import route210 from "./routes/setting/dreamina/refreshModels";
import route211 from "./routes/setting/dreamina/status";
import route212 from "./routes/setting/dreamina/uninstall";
import route213 from "./routes/setting/dreamina/update";
import route214 from "./routes/setting/dreamina/userCredit";
import route215 from "./routes/setting/fileManagement/openFolder";
import route216 from "./routes/setting/getTextModel";
import route217 from "./routes/setting/loginConfig/getUser";
import route218 from "./routes/setting/loginConfig/updateUserPwd";
import route219 from "./routes/setting/memoryConfig/delAllMemory";
import route220 from "./routes/setting/memoryConfig/getMemory";
import route221 from "./routes/setting/memoryConfig/sureMemory";
import route222 from "./routes/setting/modelMap/bindingPrompt";
import route223 from "./routes/setting/modelMap/deletePrompt";
import route224 from "./routes/setting/modelMap/getImageAndVideoModel";
import route225 from "./routes/setting/modelMap/getPromptList";
import route226 from "./routes/setting/modelMap/savePrompt";
import route227 from "./routes/setting/modelMap/updatePrompt";
import route228 from "./routes/setting/promptManage/getPrompt";
import route229 from "./routes/setting/promptManage/updatePrompt";
import route230 from "./routes/setting/skillManagement/getSkillContent";
import route231 from "./routes/setting/skillManagement/getSkillList";
import route232 from "./routes/setting/skillManagement/saveSkillContent";
import route233 from "./routes/setting/storage/createWorkspace";
import route234 from "./routes/setting/storage/scanLegacy";
import route235 from "./routes/setting/storage/startMigration";
import route236 from "./routes/setting/storage/status";
import route237 from "./routes/setting/storage/validateTarget";
import route238 from "./routes/setting/vendorConfig/addVendor";
import route239 from "./routes/setting/vendorConfig/addVendorModel";
import route240 from "./routes/setting/vendorConfig/deleteVendor";
import route241 from "./routes/setting/vendorConfig/delVendorModel";
import route242 from "./routes/setting/vendorConfig/enableVendor";
import route243 from "./routes/setting/vendorConfig/getCodeByLink";
import route244 from "./routes/setting/vendorConfig/getVendorList";
import route245 from "./routes/setting/vendorConfig/modelTest";
import route246 from "./routes/setting/vendorConfig/modelTest/imageTest";
import route247 from "./routes/setting/vendorConfig/modelTest/textTest";
import route248 from "./routes/setting/vendorConfig/modelTest/videoTest";
import route249 from "./routes/setting/vendorConfig/updateCode";
import route250 from "./routes/setting/vendorConfig/updateVendorInputs";
import route251 from "./routes/setting/vendorConfig/upVendorModel";
import route252 from "./routes/story/annotation/batchUpdateStatus";
import route253 from "./routes/story/annotation/create";
import route254 from "./routes/story/annotation/list";
import route255 from "./routes/story/annotation/updateStatus";
import route256 from "./routes/story/artifact/archive";
import route257 from "./routes/story/artifact/create";
import route258 from "./routes/story/artifact/detail";
import route259 from "./routes/story/artifact/list";
import route260 from "./routes/story/artifact/publishToScript";
import route261 from "./routes/story/artifact/update";
import route262 from "./routes/task/cancel";
import route263 from "./routes/task/getProject";
import route264 from "./routes/task/getTaskApi";
import route265 from "./routes/task/getTaskCategories";
import route266 from "./routes/task/status/snapshot";
import route267 from "./routes/task/taskDetails";
import route268 from "./routes/test/test";
import route269 from "./routes/textAsset/getContent";

export default async (app: Express) => {
  app.use("/api/agent/run/detail", route1);
  app.use("/api/agent/run/status", route2);
  app.use("/api/agents/clearMemory", route3);
  app.use("/api/agents/getMemory", route4);
  app.use("/api/artStyle/addArtStyle", route5);
  app.use("/api/artStyle/editArtStyle", route6);
  app.use("/api/artStyle/extractStylePrompt", route7);
  app.use("/api/artStyle/getArtStyle", route8);
  app.use("/api/assets/addAssets", route9);
  app.use("/api/assets/addAudioAssets", route10);
  app.use("/api/assets/batchDelete", route11);
  app.use("/api/assets/batchGenerationData", route12);
  app.use("/api/assets/delAssets", route13);
  app.use("/api/assets/delImage", route14);
  app.use("/api/assets/foundation/generate", route15);
  app.use("/api/assets/generateAssets", route16);
  app.use("/api/assets/getAssetsApi", route17);
  app.use("/api/assets/getImage", route18);
  app.use("/api/assets/getMaterialData", route19);
  app.use("/api/assets/polishAssetsPrompt", route20);
  app.use("/api/assets/pollingImageAssets", route21);
  app.use("/api/assets/pollingPromptAssets", route22);
  app.use("/api/assets/saveAssets", route23);
  app.use("/api/assets/updateAssets", route24);
  app.use("/api/assets/updateAudioAssets", route25);
  app.use("/api/assets/uploadClip", route26);
  app.use("/api/assetsGenerate/batchGenerateImageAssets", route27);
  app.use("/api/assetsGenerate/batchPolishAssetsPrompt", route28);
  app.use("/api/assetsGenerate/cancelGenerate", route29);
  app.use("/api/assetsGenerate/generateAssets", route30);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route31);
  app.use("/api/common/getBigImage", route32);
  app.use("/api/cornerScape/batchBindAudio", route33);
  app.use("/api/cornerScape/getAllAssets", route34);
  app.use("/api/cornerScape/pollingAudio", route35);
  app.use("/api/cornerScape/updateAssetsAudio", route36);
  app.use("/api/diagnostics/logs/cleanup", route37);
  app.use("/api/diagnostics/logs/export", route38);
  app.use("/api/diagnostics/logs/status", route39);
  app.use("/api/diagnostics/runtime/status", route40);
  app.use("/api/general/generalStatistics", route41);
  app.use("/api/general/getSingleProject", route42);
  app.use("/api/general/updateProject", route43);
  app.use("/api/login/login", route44);
  app.use("/api/modelSelect/getModelDetail", route45);
  app.use("/api/modelSelect/getModelList", route46);
  app.use("/api/novel/addNovel", route47);
  app.use("/api/novel/batchDeleteNovel", route48);
  app.use("/api/novel/delNovel", route49);
  app.use("/api/novel/event/batchDeleteEvent", route50);
  app.use("/api/novel/event/deletEvent", route51);
  app.use("/api/novel/event/generateEvents", route52);
  app.use("/api/novel/event/getEvent", route53);
  app.use("/api/novel/getNovel", route54);
  app.use("/api/novel/getNovelData", route55);
  app.use("/api/novel/getNovelEventState", route56);
  app.use("/api/novel/getNovelIndex", route57);
  app.use("/api/novel/updateNovel", route58);
  app.use("/api/other/deleteAllData", route59);
  app.use("/api/other/getVersion", route60);
  app.use("/api/production/assets/addDeriveAsset", route61);
  app.use("/api/production/assets/batchGenerateAssetsImage", route62);
  app.use("/api/production/assets/deleteAssetsDireve", route63);
  app.use("/api/production/assets/pollingImage", route64);
  app.use("/api/production/assets/updateAssetsUrl", route65);
  app.use("/api/production/editImage/createDirectorAsset", route66);
  app.use("/api/production/editImage/generateFlowImage", route67);
  app.use("/api/production/editImage/generateFlowImageTask", route68);
  app.use("/api/production/editImage/getAssetImageHistory", route69);
  app.use("/api/production/editImage/getImageDefaultModle", route70);
  app.use("/api/production/editImage/getImageFlow", route71);
  app.use("/api/production/editImage/getImageHistory", route72);
  app.use("/api/production/editImage/pollImageTask", route73);
  app.use("/api/production/editImage/saveImageFlow", route74);
  app.use("/api/production/editImage/updateImageFlow", route75);
  app.use("/api/production/editImage/uploadImage", route76);
  app.use("/api/production/editImage/uploadMedia", route77);
  app.use("/api/production/getFlowData", route78);
  app.use("/api/production/getStoryboardData", route79);
  app.use("/api/production/music/bible/detail", route80);
  app.use("/api/production/music/bible/generate", route81);
  app.use("/api/production/music/bible/list", route82);
  app.use("/api/production/music/bible/review", route83);
  app.use("/api/production/music/cue/bind", route84);
  app.use("/api/production/music/cue/compilePrompt", route85);
  app.use("/api/production/music/cue/generate", route86);
  app.use("/api/production/music/cue/list", route87);
  app.use("/api/production/music/cue/prompt/list", route88);
  app.use("/api/production/music/cue/prompt/save", route89);
  app.use("/api/production/music/cue/reviewPrompt", route90);
  app.use("/api/production/music/cue/selectAsset", route91);
  app.use("/api/production/music/library/compilePrompt", route92);
  app.use("/api/production/music/library/create", route93);
  app.use("/api/production/music/library/detail", route94);
  app.use("/api/production/music/library/edition/save", route95);
  app.use("/api/production/music/library/generate", route96);
  app.use("/api/production/music/library/list", route97);
  app.use("/api/production/music/library/lyrics/confirm", route98);
  app.use("/api/production/music/library/lyrics/generate", route99);
  app.use("/api/production/music/library/lyrics/list", route100);
  app.use("/api/production/music/library/lyrics/review", route101);
  app.use("/api/production/music/library/lyrics/save", route102);
  app.use("/api/production/music/library/prompt/list", route103);
  app.use("/api/production/music/library/prompt/save", route104);
  app.use("/api/production/music/library/reviewPrompt", route105);
  app.use("/api/production/music/library/selectVersion", route106);
  app.use("/api/production/music/library/trim", route107);
  app.use("/api/production/music/plan/detail", route108);
  app.use("/api/production/music/plan/generate", route109);
  app.use("/api/production/music/plan/list", route110);
  app.use("/api/production/music/plan/review", route111);
  app.use("/api/production/review/accept", route112);
  app.use("/api/production/review/createFeedback", route113);
  app.use("/api/production/review/detail", route114);
  app.use("/api/production/review/ignore", route115);
  app.use("/api/production/review/list", route116);
  app.use("/api/production/review/recalculate", route117);
  app.use("/api/production/review/resolveBatch", route118);
  app.use("/api/production/review/rollback", route119);
  app.use("/api/production/saveFlowData", route120);
  app.use("/api/production/storyboard/addStoryboard", route121);
  app.use("/api/production/storyboard/applyStoryboardTableReview", route122);
  app.use("/api/production/storyboard/batchAddStoryboardInfo", route123);
  app.use("/api/production/storyboard/batchDelete", route124);
  app.use("/api/production/storyboard/batchGenerateImage", route125);
  app.use("/api/production/storyboard/downPreviewImage", route126);
  app.use("/api/production/storyboard/editStoryboardInfo", route127);
  app.use("/api/production/storyboard/getStoryboardData", route128);
  app.use("/api/production/storyboard/pollingImage", route129);
  app.use("/api/production/storyboard/previewImage", route130);
  app.use("/api/production/storyboard/removeFrame", route131);
  app.use("/api/production/storyboard/restructureStoryboardTable", route132);
  app.use("/api/production/storyboard/reviewStoryboardTable", route133);
  app.use("/api/production/storyboard/updateStoryboardUrl", route134);
  app.use("/api/production/workbench/addTrack", route135);
  app.use("/api/production/workbench/applyVideoTrackReview", route136);
  app.use("/api/production/workbench/batchGeneratePrompt", route137);
  app.use("/api/production/workbench/batchGenerateVideo", route138);
  app.use("/api/production/workbench/cancelVideoGenerationTask", route139);
  app.use("/api/production/workbench/checkVideoPrompt", route140);
  app.use("/api/production/workbench/checkVideoStateList", route141);
  app.use("/api/production/workbench/createMergedReference", route142);
  app.use("/api/production/workbench/deleteTrack", route143);
  app.use("/api/production/workbench/delVideo", route144);
  app.use("/api/production/workbench/generateVideo", route145);
  app.use("/api/production/workbench/generateVideoPrompt", route146);
  app.use("/api/production/workbench/getAudioBindAssetsList", route147);
  app.use("/api/production/workbench/getFileUrl", route148);
  app.use("/api/production/workbench/getGenerateData", route149);
  app.use("/api/production/workbench/getVideoList", route150);
  app.use("/api/production/workbench/reviewVideoTracks", route151);
  app.use("/api/production/workbench/selectVideo", route152);
  app.use("/api/production/workbench/updateVideoDuration", route153);
  app.use("/api/production/workbench/updateVideoPrompt", route154);
  app.use("/api/project/addDirectorManual", route155);
  app.use("/api/project/addProject", route156);
  app.use("/api/project/addVisualManual", route157);
  app.use("/api/project/contextPack/generate", route158);
  app.use("/api/project/contextPack/get", route159);
  app.use("/api/project/deleteDirectorManual", route160);
  app.use("/api/project/deleteVisualManual", route161);
  app.use("/api/project/delProject", route162);
  app.use("/api/project/editDirectorlManual", route163);
  app.use("/api/project/editProject", route164);
  app.use("/api/project/editVisualManual", route165);
  app.use("/api/project/getModelDetails", route166);
  app.use("/api/project/getProject", route167);
  app.use("/api/project/getVisualManual", route168);
  app.use("/api/project/importPortableProject", route169);
  app.use("/api/project/material/delete", route170);
  app.use("/api/project/material/list", route171);
  app.use("/api/project/material/read", route172);
  app.use("/api/project/material/upload", route173);
  app.use("/api/project/preparePortableCopy", route174);
  app.use("/api/project/queryDirectorManual", route175);
  app.use("/api/project/visualManual", route176);
  app.use("/api/script/addScript", route177);
  app.use("/api/script/batchAddScript", route178);
  app.use("/api/script/delScript", route179);
  app.use("/api/script/exportScript", route180);
  app.use("/api/script/extractAssets", route181);
  app.use("/api/script/getAiRegex", route182);
  app.use("/api/script/getScrptApi", route183);
  app.use("/api/script/pollScriptAssets", route184);
  app.use("/api/script/updateScript", route185);
  app.use("/api/scriptAgent/deleteScript", route186);
  app.use("/api/scriptAgent/saveWorkspaceStage", route187);
  app.use("/api/scriptAgent/upsertScript", route188);
  app.use("/api/scriptAgent/workspaceDetail", route189);
  app.use("/api/setting/about/checkUpdate", route190);
  app.use("/api/setting/about/downloadApp", route191);
  app.use("/api/setting/agentDeploy/agentSetKey", route192);
  app.use("/api/setting/agentDeploy/deployAgentModel", route193);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route194);
  app.use("/api/setting/agentDeploy/getAgentUseMode", route195);
  app.use("/api/setting/agentDeploy/updateUseMode", route196);
  app.use("/api/setting/dbConfig/clearData", route197);
  app.use("/api/setting/dbConfig/clearTable", route198);
  app.use("/api/setting/dbConfig/dbInfo", route199);
  app.use("/api/setting/dbConfig/exportData", route200);
  app.use("/api/setting/dbConfig/importData", route201);
  app.use("/api/setting/dev/getSwitchAiDevTool", route202);
  app.use("/api/setting/dev/updateSwitchAiDevTool", route203);
  app.use("/api/setting/dreamina/install", route204);
  app.use("/api/setting/dreamina/listTask", route205);
  app.use("/api/setting/dreamina/login", route206);
  app.use("/api/setting/dreamina/logout", route207);
  app.use("/api/setting/dreamina/queryResult", route208);
  app.use("/api/setting/dreamina/queueStatus", route209);
  app.use("/api/setting/dreamina/refreshModels", route210);
  app.use("/api/setting/dreamina/status", route211);
  app.use("/api/setting/dreamina/uninstall", route212);
  app.use("/api/setting/dreamina/update", route213);
  app.use("/api/setting/dreamina/userCredit", route214);
  app.use("/api/setting/fileManagement/openFolder", route215);
  app.use("/api/setting/getTextModel", route216);
  app.use("/api/setting/loginConfig/getUser", route217);
  app.use("/api/setting/loginConfig/updateUserPwd", route218);
  app.use("/api/setting/memoryConfig/delAllMemory", route219);
  app.use("/api/setting/memoryConfig/getMemory", route220);
  app.use("/api/setting/memoryConfig/sureMemory", route221);
  app.use("/api/setting/modelMap/bindingPrompt", route222);
  app.use("/api/setting/modelMap/deletePrompt", route223);
  app.use("/api/setting/modelMap/getImageAndVideoModel", route224);
  app.use("/api/setting/modelMap/getPromptList", route225);
  app.use("/api/setting/modelMap/savePrompt", route226);
  app.use("/api/setting/modelMap/updatePrompt", route227);
  app.use("/api/setting/promptManage/getPrompt", route228);
  app.use("/api/setting/promptManage/updatePrompt", route229);
  app.use("/api/setting/skillManagement/getSkillContent", route230);
  app.use("/api/setting/skillManagement/getSkillList", route231);
  app.use("/api/setting/skillManagement/saveSkillContent", route232);
  app.use("/api/setting/storage/createWorkspace", route233);
  app.use("/api/setting/storage/scanLegacy", route234);
  app.use("/api/setting/storage/startMigration", route235);
  app.use("/api/setting/storage/status", route236);
  app.use("/api/setting/storage/validateTarget", route237);
  app.use("/api/setting/vendorConfig/addVendor", route238);
  app.use("/api/setting/vendorConfig/addVendorModel", route239);
  app.use("/api/setting/vendorConfig/deleteVendor", route240);
  app.use("/api/setting/vendorConfig/delVendorModel", route241);
  app.use("/api/setting/vendorConfig/enableVendor", route242);
  app.use("/api/setting/vendorConfig/getCodeByLink", route243);
  app.use("/api/setting/vendorConfig/getVendorList", route244);
  app.use("/api/setting/vendorConfig/modelTest", route245);
  app.use("/api/setting/vendorConfig/modelTest/imageTest", route246);
  app.use("/api/setting/vendorConfig/modelTest/textTest", route247);
  app.use("/api/setting/vendorConfig/modelTest/videoTest", route248);
  app.use("/api/setting/vendorConfig/updateCode", route249);
  app.use("/api/setting/vendorConfig/updateVendorInputs", route250);
  app.use("/api/setting/vendorConfig/upVendorModel", route251);
  app.use("/api/story/annotation/batchUpdateStatus", route252);
  app.use("/api/story/annotation/create", route253);
  app.use("/api/story/annotation/list", route254);
  app.use("/api/story/annotation/updateStatus", route255);
  app.use("/api/story/artifact/archive", route256);
  app.use("/api/story/artifact/create", route257);
  app.use("/api/story/artifact/detail", route258);
  app.use("/api/story/artifact/list", route259);
  app.use("/api/story/artifact/publishToScript", route260);
  app.use("/api/story/artifact/update", route261);
  app.use("/api/task/cancel", route262);
  app.use("/api/task/getProject", route263);
  app.use("/api/task/getTaskApi", route264);
  app.use("/api/task/getTaskCategories", route265);
  app.use("/api/task/status/snapshot", route266);
  app.use("/api/task/taskDetails", route267);
  app.use("/api/test/test", route268);
  app.use("/api/textAsset/getContent", route269);
}
